on: pull_request
name: DB tests
jobs:
  sqlite:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.5
    - name: Install go1.18 beta
      run: |
        go install golang.org/dl/go1.18beta1@latest
        go1.18beta1 download
        cp $(which go1.18beta1) $(which go)
        go version
    - name: Checkout schemable
      uses: actions/checkout@v2
      with:
        path: ./schemable
    - name: Checkout schemable_sqlitetest
      uses: actions/checkout@v2
      with:
        repository: refractionist/schemable_sqlitetest
        path: ./schemable_sqlitetest
    - name: Replace schemable mod in sqlitetest
      run: go mod edit -replace github.com/refractionist/schemable=../schemable
      working-directory: ./schemable_sqlitetest
    - name: Setup Go package caching
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod              # Module download cache
          ~/.cache/go-build         # Build cache (Linux)
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Run sqlite tests
      run: go test -v
      working-directory: ./schemable_sqlitetest