on: [push, pull_request]
name: Test
jobs:
  test:
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18beta1
    - name: Checkout schemable
      uses: actions/checkout@v2
      with:
        path: ./schemable
    - name: Checkout schemable_sqlitetest
      uses: actions/checkout@v2
      with:
        repository: refractionist/schemable_sqlitetest
        path: ./schemable_sqlitetest
    - name: Replace schemable mod in sqlitetest
      run: go mod edit -replace github.com/refractionist/schemable=../schemable
      working-directory: ./schemable_sqlitetest
    - name: Run sqlite tests
      run: go test -v
      working-directory: ./schemable_sqlitetest